version: '3.8'

services:
  web:
    image: avyakta000/ancient-baoiam-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/letsencrypt  
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./ssl:/etc/letsencrypt 
      - ./certbot/conf:/etc/letsencrypt/config 
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
