# Generated by Django 4.2 on 2024-08-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_coursecategory_file_course_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='file',
            new_name='brochure',
        ),
        migrations.AddField(
            model_name='course',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='course_banners/'),
        ),
    ]
